name: esemes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.7
  firebase_core: ^1.4.0
  google_sign_in: ^5.0.7
  firebase_auth: ^3.0.1
  lottie: 1.1.0
  introduction_screen: 2.1.0
  google_fonts: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

